// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.3.4.5

#pragma once
#ifndef WINRT_Microsoft_Graphics_DirectX_H
#define WINRT_Microsoft_Graphics_DirectX_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.3.4.5"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.3.4.5"
#include "winrt/impl/microsoft.graphics.directx.2.h"
namespace winrt::impl
{
}
WINRT_EXPORT namespace winrt::Microsoft::Graphics::DirectX
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
