set(CMAKE_BUILD_TYPE "Release")
set(CMAKE_C_COMPILER clang)
set(CMAKE_ASM_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_SYSROOT "/home/cqwrteur/toolchains/llvm/x86_64-unknown-windows-msvc/x86_64-unknown-windows-msvc")
set(CMAKE_C_COMPILER_TARGET "x86_64-unknown-windows-msvc")
set(CMAKE_CXX_COMPILER_TARGET "${CMAKE_C_COMPILER_TARGET}")
set(CMAKE_ASM_COMPILER_TARGET "${CMAKE_C_COMPILER_TARGET}")
set(CMAKE_SYSTEM_NAME "")
set(CMAKE_SYSTEM_PROCESSOR "")
set(CMAKE_CROSSCOMPILING On)
set(CMAKE_FIND_ROOT_PATH "/home/cqwrteur/toolchains/windows-msvc-sysroot")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM "NEVER")
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY "ONLY")
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE "ONLY")

find_program(CMAKE_LIPO llvm-lipo)
if (NOT CMAKE_LIPO)
    message(FATAL_ERROR "llvm-lipo not found")
endif()

find_program(CMAKE_STRIP llvm-strip)
if (NOT CMAKE_STRIP)
    message(FATAL_ERROR "llvm-strip not found")
endif()

find_program(CMAKE_NM llvm-nm)
if (NOT CMAKE_NM)
    message(FATAL_ERROR "llvm-nm not found")
endif()

find_program(CMAKE_AR llvm-ar)
if (NOT CMAKE_AR)
    message(FATAL_ERROR "llvm-ar not found")
endif()

find_program(CMAKE_RANLIB llvm-ranlib)
if (NOT CMAKE_RANLIB)
    message(FATAL_ERROR "llvm-ranlib not found")
endif()

find_program(CMAKE_INSTALL_NAME_TOOL llvm-install-name-tool)
if (NOT CMAKE_INSTALL_NAME_TOOL)
    message(FATAL_ERROR "llvm-install-name-tool not found")
endif()

find_program(CMAKE_RC_COMPILER llvm-windres)
if (NOT CMAKE_RC_COMPILER)
    message(CMAKE_RC_COMPILER "llvm-windres not found")
endif()
set(CMAKE_RC_FLAGS "--target=${CMAKE_C_COMPILER_TARGET} -I${CMAKE_FIND_ROOT_PATH}/include")

set(CMAKE_POSITION_INDEPENDENT_CODE On)
set(LLVM_ENABLE_LTO thin)
set(LLVM_ENABLE_LLD On)
set(CMAKE_C_FLAGS_INIT "-fuse-ld=lld -fuse-lipo=llvm-lipo -flto=thin -Wno-unused-command-line-argument")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_C_FLAGS_INIT}")
set(CMAKE_ASM_FLAGS_INIT "${CMAKE_C_FLAGS_INIT}")
set(CMAKE_LINKER_TYPE LLD)
set(CMAKE_C_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} -rtlib=compiler-rt")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} -rtlib=compiler-rt -stdlib=libc++ --unwindlib=libunwind")
set(CMAKE_ASM_FLAGS_INIT "${CMAKE_ASM_FLAGS_INIT} -rtlib=compiler-rt")
set(CMAKE_SIZEOF_VOID_P 4)
