include("${CMAKE_CURRENT_LIST_DIR}/common_cmake.cmake")

set(LLVM_HOST_TRIPLE x86_64-unknown-windows-msvc)
set(LLVM_DEFAULT_TARGET_TRIPLE ${LLVM_HOST_TRIPLE})
set(LLVM_ENABLE_LTO "Thin")
set(LLVM_ENABLE_LLD "On")
set(C_SUPPORTS_CUSTOM_LINKER On)
set(CXX_SUPPORTS_CUSTOM_LINKER On)
set(ASM_SUPPORTS_CUSTOM_LINKER On)
set(LLVM_ENABLE_PROJECTS clang;clang-tools-extra;lld;lldb;mlir)
set(CLANG_ENABLE_CIR On)
set(BUILD_SHARED_LIBS On)
set(LLVM_ENABLE_LIBCXX On)
set(LLVM_ENABLE_ZLIB FORCE_ON)
set(CMAKE_DISABLE_FIND_PACKAGE_CUDAToolkit On)
set(ZLIB_INCLUDE_DIR "${CMAKE_FIND_ROOT_PATH}/include")

set(LLVM_ENABLE_LIBXML2 FORCE_ON)
if(EXISTS "${CMAKE_FIND_ROOT_PATH}/include/libxml2")
set(LIBXML2_INCLUDE_DIR "${CMAKE_FIND_ROOT_PATH}/include/libxml2")
else()
set(LIBXML2_INCLUDE_DIR "${CMAKE_FIND_ROOT_PATH}/include")
endif()

if(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libz.dll.a")
set(ZLIB_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libz.dll.a")
elseif(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libzlib.dll.a")
set(ZLIB_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libzlib.dll.a")
elseif(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libzs.a")
set(ZLIB_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libzs.a")
elseif(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libzlibstatic.a")
set(ZLIB_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libzlibstatic.a")
elseif(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libz.a")
set(ZLIB_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libz.a")
elseif(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libz.tbd")
set(ZLIB_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libz.tbd")
elseif(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libz.so")
set(ZLIB_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libz.so")
elseif(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/libz.dll.a")
set(ZLIB_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/libz.dll.a")
elseif(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/libzlib.dll.a")
set(ZLIB_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/libzlib.dll.a")
elseif(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/libzs.a")
set(ZLIB_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/libzs.a")
elseif(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/libzlibstatic.a")
set(ZLIB_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/libzlibstatic.a")
elseif(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/libz.a")
set(ZLIB_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/libz.a")
elseif(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/libz.tbd")
set(ZLIB_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/libz.tbd")
else()
set(ZLIB_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/libz.so")
endif()

if(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libxml2.a")
set(LIBXML2_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libxml2.a")
elseif(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libxml2.dll.a")
set(LIBXML2_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libxml2.dll.a")
elseif(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libxml2.tbd")
set(LIBXML2_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libxml2.tbd")
elseif(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libxml2.so")
set(LIBXML2_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/x86_64-unknown-windows-msvc/libxml2.so")
elseif(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/libxml2.a")
set(LIBXML2_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/libxml2.a")
elseif(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/libxml2.dll.a")
set(LIBXML2_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/libxml2.dll.a")
elseif(EXISTS "${CMAKE_FIND_ROOT_PATH}/lib/libxml2.tbd")
set(LIBXML2_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/libxml2.tbd")
else()
set(LIBXML2_LIBRARY "${CMAKE_FIND_ROOT_PATH}/lib/libxml2.so")
endif()
set(HAVE_LIBXML2 On)
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} -lc++abi")
