include("${CMAKE_CURRENT_LIST_DIR}/common_cmake.cmake")

set(ZLIB_BUILD_TESTING Off)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
