// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_Authenticator_2_H
#define WINRT_Authenticator_2_H
#include "winrt/impl/microsoft.ui.composition.1.h"
#include "winrt/impl/microsoft.ui.xaml.1.h"
#include "winrt/impl/microsoft.ui.xaml.controls.1.h"
#include "winrt/impl/microsoft.ui.xaml.markup.1.h"
#include "winrt/impl/authenticator.1.h"
WINRT_EXPORT namespace winrt::Authenticator
{
    struct WINRT_IMPL_EMPTY_BASES Detail : winrt::Authenticator::IDetail,
        impl::base<Detail, winrt::Microsoft::UI::Xaml::Controls::Page, winrt::Microsoft::UI::Xaml::Controls::UserControl, winrt::Microsoft::UI::Xaml::Controls::Control, winrt::Microsoft::UI::Xaml::FrameworkElement, winrt::Microsoft::UI::Xaml::UIElement, winrt::Microsoft::UI::Xaml::DependencyObject>,
        impl::require<Detail, winrt::Microsoft::UI::Xaml::Controls::IPage, winrt::Microsoft::UI::Xaml::Controls::IUserControl, winrt::Microsoft::UI::Xaml::Controls::IControl, winrt::Microsoft::UI::Xaml::IFrameworkElement, winrt::Microsoft::UI::Xaml::IUIElement, winrt::Microsoft::UI::Composition::IAnimationObject, winrt::Microsoft::UI::Composition::IVisualElement, winrt::Microsoft::UI::Composition::IVisualElement2, winrt::Microsoft::UI::Xaml::IDependencyObject>
    {
        Detail(std::nullptr_t) noexcept {}
        Detail(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Authenticator::IDetail(ptr, take_ownership_from_abi) {}
        Detail();
    };
    struct WINRT_IMPL_EMPTY_BASES Settings : winrt::Authenticator::ISettings,
        impl::base<Settings, winrt::Microsoft::UI::Xaml::Controls::Page, winrt::Microsoft::UI::Xaml::Controls::UserControl, winrt::Microsoft::UI::Xaml::Controls::Control, winrt::Microsoft::UI::Xaml::FrameworkElement, winrt::Microsoft::UI::Xaml::UIElement, winrt::Microsoft::UI::Xaml::DependencyObject>,
        impl::require<Settings, winrt::Microsoft::UI::Xaml::Controls::IPage, winrt::Microsoft::UI::Xaml::Controls::IUserControl, winrt::Microsoft::UI::Xaml::Controls::IControl, winrt::Microsoft::UI::Xaml::IFrameworkElement, winrt::Microsoft::UI::Xaml::IUIElement, winrt::Microsoft::UI::Composition::IAnimationObject, winrt::Microsoft::UI::Composition::IVisualElement, winrt::Microsoft::UI::Composition::IVisualElement2, winrt::Microsoft::UI::Xaml::IDependencyObject>
    {
        Settings(std::nullptr_t) noexcept {}
        Settings(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Authenticator::ISettings(ptr, take_ownership_from_abi) {}
        Settings();
    };
    struct WINRT_IMPL_EMPTY_BASES Window : winrt::Authenticator::IWindow,
        impl::base<Window, winrt::Microsoft::UI::Xaml::Window>,
        impl::require<Window, winrt::Microsoft::UI::Xaml::IWindow, winrt::Microsoft::UI::Xaml::IWindow2>
    {
        Window(std::nullptr_t) noexcept {}
        Window(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Authenticator::IWindow(ptr, take_ownership_from_abi) {}
        Window();
    };
    struct WINRT_IMPL_EMPTY_BASES XamlMetaDataProvider : winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider
    {
        XamlMetaDataProvider(std::nullptr_t) noexcept {}
        XamlMetaDataProvider(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider(ptr, take_ownership_from_abi) {}
        XamlMetaDataProvider();
    };
}
#endif
