// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.3.4.5

#pragma once
#ifndef WINRT_Microsoft_UI_Input_Interop_1_H
#define WINRT_Microsoft_UI_Input_Interop_1_H
#include "winrt/impl/microsoft.ui.input.interop.0.h"
WINRT_EXPORT namespace winrt::Microsoft::UI::Input::Interop
{
    struct WINRT_IMPL_EMPTY_BASES IPenDeviceInteropStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IPenDeviceInteropStatics>
    {
        IPenDeviceInteropStatics(std::nullptr_t = nullptr) noexcept {}
        IPenDeviceInteropStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
