// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.3.4.5

#pragma once
#ifndef WINRT_Microsoft_UI_Composition_SystemBackdrops_2_H
#define WINRT_Microsoft_UI_Composition_SystemBackdrops_2_H
#include "winrt/impl/microsoft.ui.1.h"
#include "winrt/impl/windows.foundation.1.h"
#include "winrt/impl/microsoft.ui.composition.systembackdrops.1.h"
WINRT_EXPORT namespace winrt::Microsoft::UI::Composition::SystemBackdrops
{
    struct WINRT_IMPL_EMPTY_BASES DesktopAcrylicController : winrt::Microsoft::UI::Composition::SystemBackdrops::IDesktopAcrylicController,
        impl::require<DesktopAcrylicController, winrt::Microsoft::UI::Composition::SystemBackdrops::IDesktopAcrylicController2, winrt::Microsoft::UI::Composition::SystemBackdrops::IDesktopAcrylicController3, winrt::Windows::Foundation::IClosable, winrt::Microsoft::UI::Composition::SystemBackdrops::ISystemBackdropController, winrt::Microsoft::UI::Composition::SystemBackdrops::ISystemBackdropControllerWithTargets, winrt::Microsoft::UI::IClosableNotifier>
    {
        DesktopAcrylicController(std::nullptr_t) noexcept {}
        DesktopAcrylicController(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::Composition::SystemBackdrops::IDesktopAcrylicController(ptr, take_ownership_from_abi) {}
        DesktopAcrylicController();
        static auto IsSupported();
    };
    struct WINRT_IMPL_EMPTY_BASES MicaController : winrt::Microsoft::UI::Composition::SystemBackdrops::IMicaController,
        impl::require<MicaController, winrt::Microsoft::UI::Composition::SystemBackdrops::IMicaController2, winrt::Windows::Foundation::IClosable, winrt::Microsoft::UI::Composition::SystemBackdrops::ISystemBackdropController, winrt::Microsoft::UI::Composition::SystemBackdrops::ISystemBackdropControllerWithTargets, winrt::Microsoft::UI::IClosableNotifier>
    {
        MicaController(std::nullptr_t) noexcept {}
        MicaController(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::Composition::SystemBackdrops::IMicaController(ptr, take_ownership_from_abi) {}
        MicaController();
        static auto IsSupported();
    };
    struct WINRT_IMPL_EMPTY_BASES SystemBackdropConfiguration : winrt::Microsoft::UI::Composition::SystemBackdrops::ISystemBackdropConfiguration
    {
        SystemBackdropConfiguration(std::nullptr_t) noexcept {}
        SystemBackdropConfiguration(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::Composition::SystemBackdrops::ISystemBackdropConfiguration(ptr, take_ownership_from_abi) {}
        SystemBackdropConfiguration();
    };
}
#endif
