// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.3.4.5

#pragma once
#ifndef WINRT_Microsoft_Graphics_DirectX_2_H
#define WINRT_Microsoft_Graphics_DirectX_2_H
#include "winrt/impl/microsoft.graphics.directx.1.h"
WINRT_EXPORT namespace winrt::Microsoft::Graphics::DirectX
{
}
#endif
