// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.3.4.5

#pragma once
#ifndef WINRT_Microsoft_UI_Xaml_Automation_Text_1_H
#define WINRT_Microsoft_UI_Xaml_Automation_Text_1_H
#include "winrt/impl/microsoft.ui.xaml.automation.text.0.h"
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Automation::Text
{
}
#endif
