// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.3.4.5

#pragma once
#ifndef WINRT_Microsoft_Windows_Globalization_2_H
#define WINRT_Microsoft_Windows_Globalization_2_H
#include "winrt/impl/microsoft.windows.globalization.1.h"
WINRT_EXPORT namespace winrt::Microsoft::Windows::Globalization
{
    struct ApplicationLanguages
    {
        ApplicationLanguages() = delete;
        [[nodiscard]] static auto Languages();
        [[nodiscard]] static auto ManifestLanguages();
        [[nodiscard]] static auto PrimaryLanguageOverride();
        static auto PrimaryLanguageOverride(param::hstring const& value);
    };
}
#endif
