// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.3.4.5

#pragma once
#ifndef WINRT_Microsoft_Windows_Widgets_1_H
#define WINRT_Microsoft_Windows_Widgets_1_H
#include "winrt/impl/microsoft.windows.widgets.0.h"
WINRT_EXPORT namespace winrt::Microsoft::Windows::Widgets
{
}
#endif
