// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.3.4.5

#pragma once
#ifndef WINRT_Microsoft_UI_Input_Interop_2_H
#define WINRT_Microsoft_UI_Input_Interop_2_H
#include "winrt/impl/microsoft.ui.input.1.h"
#include "winrt/impl/microsoft.ui.input.interop.1.h"
WINRT_EXPORT namespace winrt::Microsoft::UI::Input::Interop
{
    struct PenDeviceInterop
    {
        PenDeviceInterop() = delete;
        static auto FromPointerPoint(winrt::Microsoft::UI::Input::PointerPoint const& pointerPoint);
    };
}
#endif
