// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.3.4.5

#pragma once
#ifndef WINRT_Windows_Media_Render_1_H
#define WINRT_Windows_Media_Render_1_H
#include "winrt/impl/windows.media.render.0.h"
WINRT_EXPORT namespace winrt::Windows::Media::Render
{
}
#endif
