// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.3.4.5

#pragma once
#ifndef WINRT_Windows_Security_EnterpriseData_1_H
#define WINRT_Windows_Security_EnterpriseData_1_H
#include "winrt/impl/windows.security.enterprisedata.0.h"
WINRT_EXPORT namespace winrt::Windows::Security::EnterpriseData
{
}
#endif
