#!/usr/bin/env python3
"""
patch_arm64_kuser.py -- Patch the ARM64 MSVC CRT atomics.obj stub that
hardcodes KUSER_SHARED_DATA at 0x7ffe0000.

WHY THIS PATCH EXISTS
---------------------
This sysroot is used to build Windows ARM64 binaries that are run under
Wine on Apple Silicon (macOS cannot run Windows natively).  The MSVC
static CRT startup code in atomics.obj (_InterlockedDetectSupport, CPU
feature detection for __isa_available / _AtomicsV81Support) reads
KUSER_SHARED_DATA through the hardcoded fixed address 0x7ffe0000:

    mov  x16, #0x7ffe0000        ; <-- hardcoded KUSER_SHARED_DATA
    ldrb w16, [x16, #0x296]      ; ProcessorFeatures[PF_ARM_V81_*] -> fault

On real Windows that page is always mapped, but on Apple Silicon the low
addresses are inside the kernel's page-zero region and CANNOT be mapped.
As a result EVERY binary linked against the MSVC CRT (even `int
main(){}`) FAILS TO WORK under Wine on Apple Silicon Macs -- it dies at
process start:

    wine: Unhandled page fault on read access to 000000007FFE0296

There is no portable way to locate the page from user mode: on real
Windows TPIDRRO_EL0 is not a TEB pointer (observed values: 1, 2, ... --
x18 holds the TEB there) while under Wine it points to Wine's unix
thread data with the shared page placed at TPIDRRO_EL0 - 0x1000, and the
PEB carries no KUSER pointer on either platform (UserSharedInfoPtr/0x58
and SharedData/0x90 are both NULL).  A TPIDRRO_EL0 plausibility check is
not robust -- the register is unsanctioned scratch on real Windows and
could hold a pointer-like value someday.

Since the feature byte only gates ARMv8.1 LSE atomics (the stub's bit0
selects single-instruction `ldaddal`/`casal`/`swpal` vs. the always-legal
`ldxr`/`stxr` retry loop), the patch simply makes the EL0 path report
"not supported":

    mov  w16, #0          ; feature bits = 0 -> permanent LL/SC fallback
    b    <epilogue>       ; -> orr #0x80000000 (detected), str, br x15

This is purely a performance trade-off, not a semantic one: the LL/SC
loops are the intended fallback for non-LSE silicon and are correct
everywhere, on real Windows and under Wine alike.  The EL1 path
(reading ID_AA64ISAR0_EL1 directly) is preserved, so kernel-mode
consumers of arm64rt.lib still get real feature detection.

This is a sysroot-local workaround: Microsoft's libcmt is closed source
and shipped prebuilt, so the fix must go into the shipped objects until
Microsoft relocates the access upstream.

Upstream bug report:
https://developercommunity.visualstudio.com/t/MSVC-static-CRT-ARM64-startup-hardcodes-/11133417

AFFECTED OBJECTS
----------------
The stub lives in atomics.obj, shipped (arm64 and arm64ec members) in
libcmt.lib, libcmtd.lib, msvcrt.lib, msvcrtd.lib (incl. the store/uwp/
onecore/enclave subdirectory variants) and arm64rt.lib.  Three layouts
are handled:

  * vcstartup (libcmt/libcmtd/msvcrt/msvcrtd + subdir variants):
    0x44-byte section, single KUSER read.  The EL1 (ID_AA64ISAR0_EL1)
    path is preserved for real kernel-mode detection; the EL0 block
    becomes `mov w16,#0; b epilogue; nop`.  No relocation changes.

  * nthelper (arm64rt.lib arm64 member): 0x4c-byte section, two KUSER
    reads (+0x296 and +0x2b2).  The inline EL0 read sequence becomes
    `mov w16,#0; b epilogue; nop; nop`; the EL1 fragment at the end is
    preserved.  No relocation changes.

  * nthelper-ec (arm64rt.lib arm64ec member): 0x3c-byte section, two
    KUSER reads.  The inline EL0 read sequence becomes `mov w16,#0; b
    epilogue; nop; nop`; the unreachable EL1 fragment is preserved.
    No relocation changes.

Usage:
    # emit patched .obj files to put on the link line (recommended:
    # linking the .obj directly guarantees the CRT member is never pulled)
    patch_arm64_kuser.py --emit-obj OUTDIR LIB...

    # emit a .lib archive containing the patched object
    patch_arm64_kuser.py --emit-lib kuseratomics.lib LIB...

    # patch the .lib files in place (keeps .orig backup)
    patch_arm64_kuser.py --in-place LIB...

    # default LIB list: all .lib under ROOT/lib/aarch64-unknown-windows-msvc
    # (ROOT = --sysroot, default: this sysroot, share/tools/../..)

Generated by Devin (https://devin.ai)
"""

import argparse
import os
import struct
import sys

ARMAG = b"!<arch>\n"

# Original _InterlockedDetectSupport .text (17 insns, 0x44 bytes).
# Relocs: adrp@0x4, str@0x8 (detect-in-progress marker), str@0x30 (result).
ORIG_CODE = bytes.fromhex(
    "1000b0d2"  # 00 mov  x16, #0x80000000
    "11000090"  # 04 adrp x17, _AtomicsV81Support      (PAGEBASE_REL21)
    "300200b9"  # 08 str  w16, [x17]                   (PAGEOFFSET_12L)
    "100080d2"  # 0c mov  x16, #0
    "504238d5"  # 10 mrs  x16, CurrentEL
    "100e42d3"  # 14 ubfx x16, x16, #2, #2
    "100100b4"  # 18 cbz  x16, 0x38            ; EL0 -> fixed-address read
    "100638d5"  # 1c mrs  x16, ID_AA64ISAR0_EL1        ; EL1+ path
    "105e54d3"  # 20 ubfx x16, x16, #20, #4
    "1f0a00f1"  # 24 cmp  x16, #2
    "f0379f9a"  # 28 cset x16, hs
    "100261b2"  # 2c orr  x16, x16, #0x80000000        ; epilogue
    "300200b9"  # 30 str  w16, [x17]                   (PAGEOFFSET_12L)
    "e0011fd6"  # 34 br   x15
    "d0ffafd2"  # 38 mov  x16, #0x7ffe0000     ; EL0: hardcoded KUSER (BUG)
    "105a4a39"  # 3c ldrb w16, [x16, #0x296]
    "fbffff17"  # 40 b    0x2c
)

# Patched version: the EL0 block reports "no LSE" (w16 = 0 -> the epilogue
# stores 0x80000000) so the CRT permanently uses its ldxr/stxr fallback.
# Everything before the EL0 block and the epilogue reloc are unchanged.
NEW_CODE = bytes.fromhex(
    "1000b0d2"  # 00 mov  x16, #0x80000000
    "11000090"  # 04 adrp x17, _AtomicsV81Support      (PAGEBASE_REL21)
    "300200b9"  # 08 str  w16, [x17]                   (PAGEOFFSET_12L)
    "100080d2"  # 0c mov  x16, #0
    "504238d5"  # 10 mrs  x16, CurrentEL
    "100e42d3"  # 14 ubfx x16, x16, #2, #2
    "100100b4"  # 18 cbz  x16, 0x38            ; EL0 -> constant path
    "100638d5"  # 1c mrs  x16, ID_AA64ISAR0_EL1        ; EL1+ path (kept)
    "105e54d3"  # 20 ubfx x16, x16, #20, #4
    "1f0a00f1"  # 24 cmp  x16, #2
    "f0379f9a"  # 28 cset x16, hs
    "100261b2"  # 2c orr  x16, x16, #0x80000000        ; epilogue
    "300200b9"  # 30 str  w16, [x17]                   (PAGEOFFSET_12L)
    "e0011fd6"  # 34 br   x15
    "10008052"  # 38 mov  w16, #0              ; EL0: report no LSE
    "fcffff17"  # 3c b    0x2c                 ; -> epilogue
    "1f2003d5"  # 40 nop
)

# arm64rt.lib (minkernel/crts/crtw32/helper/nt atomics.obj) variant:
# 0x4c-byte section; EL0 reads KUSER+0x296 and KUSER+0x2b2 (two feature
# bits).  EL1 branch lives at the end.
ORIG_RT_CODE = bytes.fromhex(
    "1000b0d2"  # 00 mov  x16, #0x80000000
    "11000090"  # 04 adrp x17, _AtomicsV81Support      (PAGEBASE_REL21)
    "300200b9"  # 08 str  w16, [x17]                   (PAGEOFFSET_12L)
    "100080d2"  # 0c mov  x16, #0
    "504238d5"  # 10 mrs  x16, CurrentEL
    "100e42d3"  # 14 ubfx x16, x16, #2, #2
    "100100b5"  # 18 cbnz x16, 0x38            ; EL1+ -> end fragment
    "d0ffafd2"  # 1c mov  x16, #0x7ffe0000     ; EL0: hardcoded KUSER (BUG)
    "0aca4a39"  # 20 ldrb w10, [x16, #0x2b2]
    "105a4a39"  # 24 ldrb w16, [x16, #0x296]
    "10060a2a"  # 28 orr  w16, w16, w10, lsl #1
    "100261b2"  # 2c orr  x16, x16, #0x80000000        ; epilogue
    "300200b9"  # 30 str  w16, [x17]                   (PAGEOFFSET_12L)
    "e0011fd6"  # 34 br   x15
    "100638d5"  # 38 mrs  x16, ID_AA64ISAR0_EL1        ; EL1+ path
    "105e54d3"  # 3c ubfx x16, x16, #20, #4
    "1f0a00f1"  # 40 cmp  x16, #2
    "f0379f9a"  # 44 cset x16, hs
    "f9ffff17"  # 48 b    0x2c
)

# Patched rt variant: the inline EL0 read sequence becomes `mov w16,#0;
# b epilogue; nop; nop` -- EL0 reports no LSE/LSE2 so the LL/SC fallback
# is always used in user mode.  The CurrentEL dispatch and the EL1
# (ID_AA64ISAR0_EL1) fragment at the end are preserved, so kernel-mode
# callers still get real detection.  Epilogue and both str relocs are
# unchanged.
NEW_RT_CODE = bytes.fromhex(
    "1000b0d2"  # 00 mov  x16, #0x80000000
    "11000090"  # 04 adrp x17, _AtomicsV81Support      (PAGEBASE_REL21)
    "300200b9"  # 08 str  w16, [x17]                   (PAGEOFFSET_12L)
    "100080d2"  # 0c mov  x16, #0
    "504238d5"  # 10 mrs  x16, CurrentEL
    "100e42d3"  # 14 ubfx x16, x16, #2, #2
    "100100b5"  # 18 cbnz x16, 0x38            ; EL1+ -> end fragment (kept)
    "10008052"  # 1c mov  w16, #0              ; EL0: report no LSE/LSE2
    "03000014"  # 20 b    0x2c                 ; -> epilogue
    "1f2003d5"  # 24 nop
    "1f2003d5"  # 28 nop
    "100261b2"  # 2c orr  x16, x16, #0x80000000        ; epilogue
    "300200b9"  # 30 str  w16, [x17]                   (PAGEOFFSET_12L)
    "e0011fd6"  # 34 br   x15
    "100638d5"  # 38 mrs  x16, ID_AA64ISAR0_EL1        ; EL1+ path (kept)
    "105e54d3"  # 3c ubfx x16, x16, #20, #4
    "1f0a00f1"  # 40 cmp  x16, #2
    "f0379f9a"  # 44 cset x16, hs
    "f9ffff17"  # 48 b    0x2c
)

# arm64rt.lib arm64ec variant: 0x3c-byte section.  EL0 path is inline at
# 0x0c (no CurrentEL check at all); the EL1 fragment at 0x28 is dead code
# (the only entry symbol is at 0x0 and nothing branches to 0x28).
ORIG_RT_EC_CODE = bytes.fromhex(
    "1000b0d2"  # 00 mov  x16, #0x80000000
    "11000090"  # 04 adrp x17, _AtomicsV81Support      (PAGEBASE_REL21)
    "300200b9"  # 08 str  w16, [x17]                   (PAGEOFFSET_12L)
    "d0ffafd2"  # 0c mov  x16, #0x7ffe0000     ; hardcoded KUSER (BUG)
    "0aca4a39"  # 10 ldrb w10, [x16, #0x2b2]
    "105a4a39"  # 14 ldrb w16, [x16, #0x296]
    "10060a2a"  # 18 orr  w16, w16, w10, lsl #1
    "100261b2"  # 1c orr  x16, x16, #0x80000000        ; epilogue
    "300200b9"  # 20 str  w16, [x17]                   (PAGEOFFSET_12L)
    "e0011fd6"  # 24 br   x15
    "100638d5"  # 28 mrs  x16, ID_AA64ISAR0_EL1        ; dead EL1 fragment
    "105e54d3"  # 2c ubfx x16, x16, #20, #4
    "1f0a00f1"  # 30 cmp  x16, #2
    "f0379f9a"  # 34 cset x16, hs
    "f9ffff17"  # 38 b    0x1c
)

# Patched ec variant: the inline EL0 read sequence becomes `mov w16,#0;
# b epilogue; nop; nop` -- EL0 reports no LSE/LSE2.  The epilogue and the
# dead EL1 fragment are preserved.  No relocation changes.
NEW_RT_EC_CODE = bytes.fromhex(
    "1000b0d2"  # 00 mov  x16, #0x80000000
    "11000090"  # 04 adrp x17, _AtomicsV81Support      (PAGEBASE_REL21)
    "300200b9"  # 08 str  w16, [x17]                   (PAGEOFFSET_12L)
    "10008052"  # 0c mov  w16, #0              ; EL0: report no LSE/LSE2
    "03000014"  # 10 b    0x1c                 ; -> epilogue
    "1f2003d5"  # 14 nop
    "1f2003d5"  # 18 nop
    "100261b2"  # 1c orr  x16, x16, #0x80000000        ; epilogue
    "300200b9"  # 20 str  w16, [x17]                   (PAGEOFFSET_12L)
    "e0011fd6"  # 24 br   x15
    "100638d5"  # 28 mrs  x16, ID_AA64ISAR0_EL1        ; dead EL1 fragment
    "105e54d3"  # 2c ubfx x16, x16, #20, #4
    "1f0a00f1"  # 30 cmp  x16, #2
    "f0379f9a"  # 34 cset x16, hs
    "f9ffff17"  # 38 b    0x1c
)

KUSER_INSN = bytes.fromhex("d0ffafd2")  # mov x16, #0x7ffe0000

# Patched-code signatures, used to detect files already patched (skip them)
NEW_CODES = (NEW_CODE, NEW_RT_CODE, NEW_RT_EC_CODE)

# ARM64 COFF relocation types we care about
IMAGE_REL_ARM64_PAGEBASE_REL21 = 0x0004
IMAGE_REL_ARM64_PAGEOFFSET_12L = 0x0007

# (variant name, original code, patched code, {reloc VA: new VA})
PATCHES = [
    ("vcstartup", ORIG_CODE, NEW_CODE, {}),
    ("nthelper", ORIG_RT_CODE, NEW_RT_CODE, {}),
    ("nthelper-ec", ORIG_RT_EC_CODE, NEW_RT_EC_CODE, {}),
]


def iter_ar_members(data):
    """Yield (name, data_offset, size) for each member of a COFF archive."""
    if not data.startswith(ARMAG):
        raise ValueError("not an ar archive")
    longnames = b""
    off = len(ARMAG)
    while off + 60 <= len(data):
        hdr = data[off:off + 60]
        if hdr[58:60] != b"`\n":
            raise ValueError("bad archive member header at %#x" % off)
        name = hdr[0:16].decode("ascii", "replace").rstrip()
        size = int(hdr[48:58].decode("ascii").strip() or "0")
        moff = off + 60
        if name == "//":
            longnames = data[moff:moff + size]
            yield "//", moff, size
        elif name.startswith("/") and name[1:].isdigit():
            n = int(name[1:])
            e0 = longnames.find(b"\0", n)
            e1 = longnames.find(b"\n", n)
            ends = [e for e in (e0, e1) if e >= 0]
            end = min(ends) if ends else len(longnames)
            yield longnames[n:end].rstrip(b"\r\n/").decode("utf-8", "replace"), moff, size
        else:
            yield name.rstrip("/"), moff, size
        off = moff + size + (size & 1)


def is_coff_arm64(b):
    return len(b) >= 20 and struct.unpack_from("<H", b, 0)[0] in (0xAA64, 0xA641)


def scan_obj(buf):
    """Scan every section of a COFF object for the hardcoded
    `mov x16, #0x7ffe0000` instruction.  Locations are found purely by
    the instruction byte pattern -- never by member name or file offset.

    Returns (sites, patched, messages):
      sites   -- number of occurrences of the bad instruction found
      patched -- number of those occurrences inside a section whose full
                 byte layout matched a known variant (and was rewritten)
      messages-- human-readable log lines
    Sections that contain the instruction but do not match a known layout
    are reported and left alone.
    """
    out = []
    sites = patched = 0
    machine, nsec = struct.unpack_from("<HH", buf, 0)
    for i in range(nsec):
        off = 20 + i * 40
        (name, vsize, vaddr, rsize, rptr,
         relptr, lnptr, nrel, nln, chars) = struct.unpack_from("<8sIIIIIIHHI", buf, off)
        sec = bytes(buf[rptr:rptr + rsize])
        n = sec.count(KUSER_INSN)
        if not n:
            continue
        sites += n
        for vname, orig, new, reloc_moves in PATCHES:
            if sec != orig:
                continue
            seen = set()
            ok = True
            for j in range(nrel):
                va, si, ty = struct.unpack_from("<IIH", buf, relptr + j * 10)
                if va not in reloc_moves:
                    continue
                if ty != IMAGE_REL_ARM64_PAGEOFFSET_12L:
                    ok = False
                    break
                struct.pack_into("<I", buf, relptr + j * 10, reloc_moves[va])
                seen.add(va)
            if not ok or seen != set(reloc_moves):
                out.append("sec %d %s: %s reloc mismatch; SKIPPED" % (i + 1, name, vname))
                break
            buf[rptr:rptr + rsize] = new
            patched += n
            out.append("sec %d %s: patched _InterlockedDetectSupport (%s; "
                       "EL0 -> constant \"no LSE\", LL/SC fallback)%s" %
                       (i + 1, name, vname,
                        "".join(", reloc %#x->%#x" % (a, b) for a, b in reloc_moves.items())))
            break
        else:
            out.append("sec %d %s: 0x7ffe0000 insn x%d, unknown layout; SKIPPED" % (i + 1, name, n))
    return sites, patched, out


def patch_lib(path, in_place):
    """Patch one .lib file.  The file is only rewritten if *every*
    occurrence of the bad instruction was recognised and patched; if the
    counts do not match the file is reported and left untouched."""
    data = bytearray(open(path, "rb").read())
    patched = []
    sites = npatched = 0
    for name, moff, msize in iter_ar_members(bytes(data)):
        if name in ("//", "/") or msize < 20:
            continue
        mem = data[moff:moff + msize]
        if not is_coff_arm64(mem):
            continue
        mbuf = bytearray(mem)
        s, p, res = scan_obj(mbuf)
        sites += s
        npatched += p
        if res:
            data[moff:moff + msize] = mbuf
            patched.append((name, res))
    if sites != npatched:
        return patched, sites, npatched, False
    if in_place and npatched:
        bak = path + ".orig"
        st = os.stat(path)
        if not os.path.exists(bak):
            os.rename(path, bak)
        open(path, "wb").write(bytes(data))
        os.chmod(path, st.st_mode)
    return patched, sites, npatched, True


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sysroot", metavar="ROOT",
                    default=os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "..")),
                    help="repository (sysroot) root; libs default to "
                         "ROOT/lib/aarch64-unknown-windows-msvc/**/*.lib")
    ap.add_argument("libs", nargs="*",
                    help=".lib files to patch (default: all .lib under the sysroot triplet dir)")
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--emit-obj", metavar="DIR",
                   help="write patched atomics objects into DIR")
    g.add_argument("--emit-lib", metavar="FILE",
                   help="write a .lib containing the patched objects")
    g.add_argument("--in-place", action="store_true",
                   help="patch the .lib files in place (keeps .orig backup)")
    g.add_argument("--check", action="store_true",
                   help="only report what would be patched")
    args = ap.parse_args()

    libs = args.libs
    if not libs:
        import glob
        libdir = os.path.join(args.sysroot, "lib", "aarch64-unknown-windows-msvc")
        libs = sorted(glob.glob(os.path.join(libdir, "**", "*.lib"), recursive=True))

    any_hit = False
    already = 0
    emitted = []
    skipped = []
    for lib in libs:
        data = open(lib, "rb").read()
        sites = npatched = 0
        members = []
        for name, moff, msize in iter_ar_members(data):
            if name in ("//", "/") or msize < 20:
                continue
            mem = data[moff:moff + msize]
            if not is_coff_arm64(mem):
                continue
            mbuf = bytearray(mem)
            s, p, res = scan_obj(mbuf)
            sites += s
            npatched += p
            if res:
                members.append((name, mbuf, res))
        if sites and sites != npatched:
            skipped.append(lib)
            print("%s: %d occurrence(s) of mov x16,#0x7ffe0000 but only %d "
                  "matched a known layout -- FILE LEFT UNTOUCHED" %
                  (lib, sites, npatched), file=sys.stderr)
            for name, mbuf, res in members:
                for r in res:
                    print("    %s: %s" % (os.path.basename(name), r), file=sys.stderr)
            continue
        if not npatched:
            if not sites and any(nc in data for nc in NEW_CODES):
                already += 1
                print("%s: already patched, skipping" % lib)
            continue
        any_hit = True
        for name, mbuf, res in members:
            tag = "arm64ec" if struct.unpack_from("<H", mbuf, 0)[0] == 0xA641 else "arm64"
            for r in res:
                print("%s [%s/%s]: %s" % (os.path.basename(lib), tag,
                                          os.path.basename(name), r))
            if args.emit_obj:
                os.makedirs(args.emit_obj, exist_ok=True)
                stem = os.path.splitext(os.path.basename(lib))[0]
                out = os.path.join(args.emit_obj, "%s_%s_atomics.obj" % (stem, tag))
                open(out, "wb").write(bytes(mbuf))
                emitted.append(out)
            elif args.emit_lib:
                emitted.append(("%s_%s_atomics.obj" %
                                (os.path.splitext(os.path.basename(lib))[0], tag),
                                bytes(mbuf)))
        if args.in_place:
            patch_lib(lib, True)
            print("%s: patched in place (backup: %s.orig)" % (lib, lib))

    if args.emit_lib and emitted:
        out = bytearray(ARMAG)
        for mname, mdata in emitted:
            hdr = ("%-16s%-12d%-6d%-6d%-8o%-10d`\n" %
                   (mname + "/", 0, 0, 0, 0o644, len(mdata))).encode()
            out += hdr + mdata
            if len(mdata) & 1:
                out += b"\n"
        open(args.emit_lib, "wb").write(bytes(out))
        print("wrote %s" % args.emit_lib)
    for e in emitted:
        if isinstance(e, str):
            print("wrote %s" % e)
    if not any_hit:
        if already:
            print("all files already patched, nothing to do")
            return 0
        print("no hardcoded KUSER stub found", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
